import numpy as np
joint_name = [
"Humano_BoneRoot",
"Humano_Hip",
"Humano_Pelvis",
'Humano_L_Thigh',
'Humano_L_Calf',
'Humano_L_Foot',
'Humano_L_ToeBase',
'Humano_L_CalfTwist01',
'Humano_L_CalfTwist02',
"Humano_L_ThighTwist01",
'Humano_L_ThighTwist02',
'Humano_R_Thigh',
'Humano_R_ThighTwist01',
'Humano_R_ThighTwist02',
'Humano_R_Calf',
'Humano_R_Foot',
'Humano_R_ToeBase',
'Humano_R_CalfTwist01',
'Humano_R_CalfTwist02',
'Humano_Waist',
'Humano_Spine01',
'Humano_Spine02',
'Humano_NeckTwist01',
'Humano_NeckTwist02',
'Humano_Head',
'Humano_R_Eye',
'Humano_L_Eye',
'Humano_L_Clavicle',
'Humano_L_Upperarm',
'Humano_L_Forearm',
'Humano_L_ForearmTwist01',
'Humano_L_ForearmTwist02',
'Humano_L_Hand',
'Humano_L_Mid1',
'Humano_L_Mid2',
'Humano_L_Mid3',
'Humano_L_Index1',
'Humano_L_Index2',
'Humano_L_Index3',
'Humano_L_Ring1',
'Humano_L_Ring2',
'Humano_L_Ring3',
'Humano_L_Pinky1',
'Humano_L_Pinky2',
'Humano_L_Pinky3',
'Humano_L_Thumb1',
'Humano_L_Thumb2',
'Humano_L_Thumb3',
'Humano_L_UpperarmTwist01',
'Humano_L_UpperarmTwist02',
'Humano_R_Clavicle',
'Humano_R_Upperarm',
'Humano_R_UpperarmTwist01',
'Humano_R_UpperarmTwist02',
'Humano_R_Forearm',
'Humano_R_ForearmTwist01',
'Humano_R_ForearmTwist02',
'Humano_R_Hand',
'Humano_R_Mid1',
'Humano_R_Mid2',
'Humano_R_Mid3',
'Humano_R_Ring1',
'Humano_R_Ring2',
'Humano_R_Ring3',
'Humano_R_Thumb1',
'Humano_R_Thumb2',
'Humano_R_Thumb3',
'Humano_R_Index1',
'Humano_R_Index2',
'Humano_R_Index3',
'Humano_R_Pinky1',
'Humano_R_Pinky2',
'Humano_R_Pinky3',
'Humano_R_RibsTwist',
'Humano_R_Breast',
'Humano_L_RibsTwist',
'Humano_L_Breast',
]

joint_map = {
"Humano_Hip": "pelvis",
"Humano_Pelvis": "spine1",
'Humano_Spine01': "spine1",
'Humano_Spine02': "spine2",
'Humano_L_Clavicle': "left_collar",
'Humano_L_Upperarm': "left_shoulder",
'Humano_L_Forearm': "left_elbow",
'Humano_L_Hand': "left_wrist",
'Humano_L_Mid1': "left_middle1",
'Humano_L_Mid2': "left_middle2",
'Humano_L_Mid3': "left_middle3",
'Humano_L_Index1': "left_index1",
'Humano_L_Index2': "left_index2",
'Humano_L_Index3': "left_index3",
'Humano_L_Ring1': "left_ring1",
'Humano_L_Ring2': "left_ring2",
'Humano_L_Ring3': "left_ring3",
'Humano_L_Pinky1': "left_pinky1",
'Humano_L_Pinky2': "left_pinky2",
'Humano_L_Pinky3': "left_pinky3",
'Humano_L_Thumb1': "left_thumb1",
'Humano_L_Thumb2': "left_thumb2",
'Humano_L_Thumb3': "left_thumb3",
'Humano_R_Clavicle': "right_collar",
'Humano_R_Upperarm': "right_shoulder",
'Humano_R_Forearm': "right_elbow",
'Humano_R_Hand': "right_wrist",
'Humano_R_Mid1': "right_middle1",
'Humano_R_Mid2': "right_middle2",
'Humano_R_Mid3': "right_middle3",
'Humano_R_Ring1': "right_ring1",
'Humano_R_Ring2': "right_ring2",
'Humano_R_Ring3': "right_ring3",
'Humano_R_Thumb1': "right_thumb1",
'Humano_R_Thumb2': "right_thumb2",
'Humano_R_Thumb3': "right_thumb3",
'Humano_R_Index1': "right_index1",
'Humano_R_Index2': "right_index2",
'Humano_R_Index3': "right_index3",
'Humano_R_Pinky1': "right_pinky1",
'Humano_R_Pinky2': "right_pinky2",
'Humano_R_Pinky3': "right_pinky3",
}